accounts/urls.py
from django.urls import path
from .views import LoginView, RegisterView, index, DashboardView,UserLogoutView
app_name = 'accounts'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    # path('home/', index, name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler403, handler404
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("inventoryCEO/", admin.site.urls),
    path("", include("accounts.urls")),
    path("shipments/", include("shipments.urls")),
    path("orders/", include("orders.urls")),
    path("factories/", include("factories.urls")),
    path("inventory/", include("inventory.urls", namespace="inventory")),
    path("supermarkets/", include("supermarkets.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]
    )

if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

inventory/urls.py
from django.urls import path
from . import views
app_name = 'inventory'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('create/', views.create_product, name='product_create'),
    path('update/<int:pk>/', views.product_update, name='product_update'),
    path('delete/<int:pk>/', views.product_delete, name='product_delete'),
]

templates/compontents/aside.html
{% load static %}

<aside class="sidebar">
  <h4 class="text-center text-white text-capitalize fw-bold my-3">
    justice league
  </h4>
  <hr />
  {% if user.is_authenticated and user.role == "manager" %}
  <a
    class="nav-link {% if 'dashboard' in request.path %}active{% endif %}"
    href="{% url 'accounts:dashboard' %}">
    <i class="fas fa-home"></i> Dashboard
  </a>
  {% endif %}
  <a
    class="nav-link {% if 'orders' in request.path %}active{% endif %}"
    href="{% url 'orders' %}">
    <i class="fas fa-chart-bar"></i> Orders
  </a>

  <a
    class="nav-link {% if 'shipments' in request.path %}active{% endif %}"
    href="{% url 'shipment_list' %}">
    <i class="fas fa-truck"></i> Shipments
  </a>

  <a
    class="nav-link {% if 'inventory' in request.path %}active{% endif %}"
    href="{% url 'inventory:product_list' %}">
    <i class="fas fa-box"></i> Inventory
  </a>

  <a
    class="nav-link {% if 'factories' in request.path %}active{% endif %}"
    href="{% url 'factory_list' %}">
    <i class="fas fa-industry"></i> Factories
  </a>

  <a
    class="nav-link {% if 'supermarkets' in request.path %}active{% endif %}"
    href="{% url 'supermarket_list' %}">
    <i class="fas fa-store"></i> Supermarkets
  </a>

  <hr />

  {% if user.is_authenticated %}
  <form
    method="post"
    action="{% url 'accounts:logout' %}"
    class="d-inline from">
    {% csrf_token %}
    <button
      type="submit"
      class="nav-link"
      style="background-color: transparent; border: none; color: #fff">
      <i class="fas fa-sign-out-alt"></i> Logout
    </button>
  </form>
  {% else %}
  <a class="nav-link" href="{% url 'accounts:login' %}"
    ><i class="fas fa-sign-in-alt"></i> Login</a
  >
  {% endif %}
</aside>

templates/compontents/nav.html
{% load static %} {% load nav_tags %}

<nav class="navbar navbar-expand-lg navbar-custom">
  <div class="container-fluid">
    <button
      class="burger-btn d-block d-md-none"
      aria-label="Toggle Sidebar"
      aria-expanded="false">
      <i class="fas fa-bars"></i>
    </button>
    <a class="navbar-brand" href="#"> {% get_section_name request.path %} </a>

    <div class="d-flex align-items-center">
      <div class="dropdown">
        <a
          class="profile text-dark btn"
          href="#"
          role="button"
          id="userDropdown"
          data-bs-toggle="dropdown"
          aria-expanded="false"
          aria-label="User menu for {{ user.username }}">
          <span
            class="d-flex align-items-center gap-2 text-start text-capitalize">
            {{ user.username }}<br />
            <small class="text-muted">({{ user.role }})</small>
            <i class="fa-solid fa-caret-down"></i>
          </span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="userDropdown">
          {%if user.is_authenticated and user.role == "manager"%}
          <li>
            <a class="dropdown-item" href="{% url 'accounts:register' %}"
              >Add user</a
            >
          </li>
          {% endif %} {% if user.is_authenticated %}
          <li>
            <form
              method="post"
              action="{% url 'accounts:logout' %}"
              class="d-inline">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Logout</button>
            </form>
          </li>
          {% else %}
          <li>
            <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>